#server:
#  port: 8443
#  ssl:
#    key-store-type: PKCS12
#    key-store: classpath:keystore.p12
#    key-store-password: ${keystore_password}
#    key-alias: tomcat
#security:
#  requite-ssl: true
spring:
  jackson:
    serialization:
      fail-on-empty-beans: false
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
#  security:
#    user:
#      name: domipapa
#      password: lmaokek
  datasource:
    url: jdbc:mysql://localhost:3307/tinyexpense
    username: localuser
    password: localpass
  jpa:
    hibernate:
      ddl-auto: update
      properties:
        hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true

