spring:
  jackson:
    serialization:
      fail-on-empty-beans: false
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
server:
  port : 8080
#logging:
#  level:
#    root: WARN
#    web: INFO
#    com:
#      example: DEBUG
token:
  # one year valid jwt
  expirationms: 31556952000
  # JWT secret key
  # node -e "console.log(require('crypto').randomBytes(32).toString('hex'))"
  secret:
    key: ${JWT_SECRET_KEY}